# Generated by Django 3.2.4 on 2022-03-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'delivered'), ('2', 'out for delivery'), ('3', 'on the way'), ('4', 'order processing'), ('5', 'order placed')], max_length=40, null=True),
        ),
    ]
