# Generated by Django 3.2.4 on 2022-03-31 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='time',
            new_name='delivered_time',
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='image',
            field=models.ImageField(blank=True, default='orders/orders.png', null=True, upload_to='orders'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orders',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
