# Generated by Django 3.2.4 on 2022-03-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20220331_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
