# Generated by Django 4.0.4 on 2022-04-29 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0028_remove_post_category_remove_post_likes_and_more'),
        ('sales', '0007_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='shareme.products'),
        ),
    ]
