# Generated by Django 4.0.4 on 2022-05-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_orders_city_orders_email_orders_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='mobile',
            new_name='phone',
        ),
    ]
