# Generated by Django 4.0.4 on 2022-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'delivered'), (2, 'out for delivery'), (3, 'on the way'), (4, 'order processing'), (5, 'order placed'), (6, 'shipped')], default=5, max_length=40, null=True),
        ),
    ]
