# Generated by Django 4.0.4 on 2022-05-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'order placed'), (2, 'order processing'), (3, 'shipped'), (4, 'on the way'), (5, 'out for delivery'), (6, 'delivered')], default=1, max_length=40, null=True),
        ),
    ]
