# Generated by Django 2.2.14 on 2022-05-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
