# Generated by Django 3.2.4 on 2022-02-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'single'), ('2', 'married'), ('3', 'committed'), ('4', 'prefered not to say')], default='4', max_length=50, null=True)),
            ],
        ),
    ]
