# Generated by Django 3.2.4 on 2022-02-11 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20220211_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='college',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='hobby',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='image',
            field=models.ImageField(blank=True, default='accounts/profile1.jpg', null=True, upload_to='accounts/'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='school',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'single'), ('2', 'married'), ('3', 'committed'), ('4', 'prefered not to say')], default='4', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='work',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
