# Generated by Django 3.2.4 on 2022-03-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220314_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
