# Generated by Django 3.2.4 on 2022-03-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220327_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
