# Generated by Django 3.2.4 on 2022-04-14 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_alter_userprofilemodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='text',
            field=models.ManyToManyField(blank=True, related_name='text', to=settings.AUTH_USER_MODEL),
        ),
    ]
