# Generated by Django 3.2.4 on 2022-04-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofilemodel_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='college',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='school',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='work',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='recent_vposts',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
