# Generated by Django 2.2.14 on 2022-05-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220416_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
