# Generated by Django 3.2.4 on 2022-01-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='a', max_length=100, unique_for_date='posted'),
        ),
    ]
