# Generated by Django 3.2.4 on 2022-03-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0006_auto_20220311_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
