# Generated by Django 3.2.4 on 2022-03-25 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0012_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
