# Generated by Django 3.2.4 on 2022-03-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0013_cart_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_a',
            field=models.ImageField(blank=True, default='posts/def_post.jpeg', null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_b',
            field=models.ImageField(blank=True, default='posts/def_post.jpeg', null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_c',
            field=models.ImageField(blank=True, default='posts/def_post.jpeg', null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, unique_for_date='posted'),
        ),
    ]
