# Generated by Django 3.2.4 on 2022-03-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0014_auto_20220328_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
