# Generated by Django 3.2.4 on 2022-03-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0015_cart_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='a', max_length=100, unique_for_date='posted'),
        ),
    ]
