# Generated by Django 3.2.4 on 2022-03-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0016_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, default='cart/cart.png', null=True, upload_to='cart'),
        ),
    ]
