# Generated by Django 3.2.4 on 2022-04-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0017_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='units_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
