# Generated by Django 3.2.4 on 2022-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0018_post_units_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='total_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
