# Generated by Django 3.2.4 on 2022-04-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0020_savelater'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='post',
            name='data',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, unique_for_date='posted'),
        ),
    ]
