# Generated by Django 3.2.4 on 2022-04-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0022_auto_20220416_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_image',
            field=models.ImageField(default='comments/def_comment.jpg', upload_to='comment'),
        ),
    ]
