# Generated by Django 3.2.4 on 2022-04-20 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0023_comment_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
