# Generated by Django 3.2.4 on 2022-04-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0024_comment_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
