# Generated by Django 3.2.4 on 2022-04-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0026_alter_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, default='cart/cart.png', null=True, upload_to='cart'),
        ),
    ]
