# Generated by Django 4.0.4 on 2022-04-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0029_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
