# Generated by Django 4.0.4 on 2022-04-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0030_localcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='products',
            name='url',
        ),
    ]
