# Generated by Django 4.0.4 on 2022-05-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0032_alter_products_image_alter_products_image_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='products/def_product.png', null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_a',
            field=models.ImageField(blank=True, default='products/def_product.png', null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_b',
            field=models.ImageField(blank=True, default='products/def_product.png', null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_c',
            field=models.ImageField(blank=True, default='products/def_product.png', null=True, upload_to='products'),
        ),
    ]
