# Generated by Django 4.0.4 on 2022-05-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0035_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
