# Generated by Django 4.0.4 on 2022-05-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0037_alter_products_review_likes_alter_products_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='review_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='total_reviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='units_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
