# Generated by Django 4.0.4 on 2022-05-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0038_alter_products_review_likes_alter_products_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='activityscore',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
