# Generated by Django 3.2.4 on 2022-03-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groupchat_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchat',
            old_name='sender',
            new_name='sender_id',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
