# Generated by Django 3.2.4 on 2022-03-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='data',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
