# Generated by Django 3.2.4 on 2022-03-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_messages_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='reciever_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
