# Generated by Django 3.2.4 on 2022-03-24 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20220323_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('data', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('seen', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
