# Generated by Django 3.2.4 on 2022-03-26 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_notifications_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='reciever_many',
            field=models.ManyToManyField(blank=True, null=True, related_name='notification_multi_reciever', to=settings.AUTH_USER_MODEL),
        ),
    ]
