# Generated by Django 4.0.4 on 2022-05-09 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0011_alter_notifications_reciever_many'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='reciever_many',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.AddField(
            model_name='notifications',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
