# Generated by Django 4.0.4 on 2022-05-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_notifications_reciever_many_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='data',
            new_name='reciever_data',
        ),
        migrations.AddField(
            model_name='notifications',
            name='reciever_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='sender_data',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='sender_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
