# Generated by Django 2.2.14 on 2022-05-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_rename_data_notifications_reciever_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sender_image',
            field=models.ImageField(blank=True, default='msg.png', null=True, upload_to='mesages'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
